runtime-job-worker/pom.xml
runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/ConnectorConfig.java
runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/ConnectorJobHandler.java
runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/Main.java
runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/ConnectorJobHandlerSecretsTest.java
runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/ConnectorJobHandlerTest.java
runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/JobBuilder.java
runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/TestSecretProvider.java

Wraps the connector function result in a map before passing it
on to Zeebe. The result is only returned if a `resultVariable`
header is defined on the task (consistent with C8 SaaS Bridge behavior).
* related to #8 (has a broader scope including evaluating `resultExpression` with FEEL, for example)
* closes #45

fix: call Zeebe with result variable map

---

.gitignore
core/src/main/java/io/camunda/connector/api/ConnectorFunction.java
core/src/main/java/io/camunda/connector/api/SecretStore.java
core/src/main/java/io/camunda/connector/impl/AbstractConnectorContext.java
core/src/main/java/io/camunda/connector/test/ConnectorContextBuilder.java
core/src/test/java/io/camunda/connector/impl/ConnectorContextTest.java
core/src/test/java/io/camunda/connector/impl/TestInput.java
core/src/test/java/io/camunda/connector/impl/secrets/InputNestedObject.java
core/src/test/java/io/camunda/connector/impl/secrets/InputNumberArray.java
core/src/test/java/io/camunda/connector/impl/secrets/InputNumberList.java
core/src/test/java/io/camunda/connector/impl/secrets/InputNumberMap.java
core/src/test/java/io/camunda/connector/impl/secrets/InputNumberSet.java
core/src/test/java/io/camunda/connector/impl/secrets/InputObjectArray.java
core/src/test/java/io/camunda/connector/impl/secrets/InputObjectList.java
core/src/test/java/io/camunda/connector/impl/secrets/InputObjectMap.java
core/src/test/java/io/camunda/connector/impl/secrets/InputObjectSet.java
core/src/test/java/io/camunda/connector/impl/secrets/InputStringArray.java
core/src/test/java/io/camunda/connector/impl/secrets/InputStringList.java
core/src/test/java/io/camunda/connector/impl/secrets/InputStringListImmutable.java
core/src/test/java/io/camunda/connector/impl/secrets/InputStringMap.java
core/src/test/java/io/camunda/connector/impl/secrets/InputStringMapImmutable.java
core/src/test/java/io/camunda/connector/impl/secrets/InputStringSet.java
core/src/test/java/io/camunda/connector/test/ConnectorContextBuilderTest.java
core/src/test/java/io/camunda/connector/test/ConnectorFunctionTest.java
validation/src/test/java/io/camunda/connector/validation/ValidationProviderTest.java

Supports replacing secrets in Java Maps. Also enables replacing String secrets in Lists, Arrays, and Maps directly.
closes #78

feat: support secret replacement on maps

---

README.md
core/README.md
core/src/main/java/io/camunda/connector/api/annotation/OutboundConnector.java
core/src/main/java/io/camunda/connector/impl/ConnectorUtil.java
core/src/main/java/io/camunda/connector/impl/outbound/OutboundConnectorConfiguration.java
core/src/test/java/io/camunda/connector/impl/ConnectorUtilTest.java

Adds the `OutboundConnector` annotation to use to discover default connector configuration.
Related to https://github.com/camunda/connector-sdk/issues/12

feat: add `OutboundConnector` annotation

---

README.md
core/README.md
core/src/main/java/io/camunda/connector/api/annotation/OutboundConnector.java
core/src/main/java/io/camunda/connector/impl/ConnectorUtil.java
core/src/main/java/io/camunda/connector/impl/outbound/OutboundConnectorConfiguration.java
core/src/test/java/io/camunda/connector/impl/ConnectorUtilTest.java

Aligns it with our (albeit ambiguous) documentation and also pins us less to Zeebe specifics ("Job worker").
As discussed with @tmetzke we're already talking about the generic _type_ in some of our places. Let us establish it ("connector run-times have a _type_ of task / job / whatever they can execute").
Related to #12

chore: rename `OutboundConnector#{taskType -> type}`

---

runtime-job-worker/README.md

Users will otherwise run into missing dependency issues.

docs(runtime-job-worker): feature `-with-dependencies` bundles

---

runtime-job-worker/README.md

Ensure the job worker run-time run-instructions can actually be executed by the community (no enterprise only connectors featured).

docs(runtime-job-worker): use HTTP JSON connector in example

---

runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/api/outbound/ConnectorJobHandler.java

To reduce the number of FEEL engines created we can instantiate the FEEL engine wrapper statically in the ConnectorJobHandler similar to the ObjectMapper. The FEEL engine wrapper bundles a FEEL engine and an ObjectMaper both of them should be thread safe.
closes #121

Instantiate FEEL engine wrapper statically

---

runtime-job-worker/README.md

Fix the classpath examples to use `:` instead of `;`.
related to https://github.com/jwulf/connector-sdk/pull/1

fix: use colon for classpath resources

---

.github/workflows/CI.yml
runtime-job-worker/Dockerfile

- ensure we can build the docker image during CI
- lint dockerfile for best practies using hadolint
- use COPY instead of ADD to add local files as recommend by hadolint

Add docker build and liniting to CI

---

runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/impl/feel/FeelEngineWrapper.java
runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/api/outbound/ConnectorJobHandlerTest.java
runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/impl/feel/FeelEngineWrapperExpressionEvaluationTest.java

To support POJO responses of the connector function use the jackson object mapper to ensure that response can be casted to a map.
closes #135

fix(runtime): use object mapper to convert to map

---

runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/impl/feel/FeelEngineWrapper.java
runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/api/outbound/ConnectorJobHandlerTest.java

This PR ignores fields of a response, which are not know types for the object mapper. I decided to ignore them to gracefully handle the response instead of failing.
- Add test to verify null values are handled correctly
- Add test to verify unknown object values are ignore
related to #153

Ignore unknown object values in response

---

licenses/third-party.ftl
parent/pom.xml

Adds support for the following licenses in our TPL file:
* Apache License
* Eclipse Public License v. 1.0
* EPL-1.0
* Eclipse Public License - v 1.0
* EPL 2.0
* GNU Lesser General Public License, Version 2.1
* GNU Lesser General Public License
closes #207

chore: add more supported third-party licenses

---

core/README.md

This PR fixes the broken link in [`./core/README.md`](https://github.com/camunda/connector-sdk/blob/c3e7b0828458774660a97ec6033295d74547841e/core/README.md?plain=1#L34). The reason of the problem is the same as described in PR #211 (I did not spot it then).
There no related issue.

docs: fix broken link to `runtime`

---

validation/README.md

This PR fixes the dead link in [`./validation/README.md`](https://github.com/camunda/connector-sdk/blob/d278f8be151c2ef7b08f56a5bda09d6b592ebcd8/validation/README.md?plain=1#L118).
There is no related issue.

docs: add missing `.` in `ValidationProvider` link

---

runtime/pom.xml

Includes the validation module by default in the `runtime`. This provides the module so Connectors can consume it if they want to. Connectors (optionally) depend on the validation module with scope `provided`. Thus, as their runtime, we need to provide it here.
related to https://github.com/camunda/team-connectors/issues/209

chore(runtime): include validation module

---

core/src/main/java/io/camunda/connector/api/inbound/InboundConnectorContext.java
core/src/main/java/io/camunda/connector/impl/context/AbstractConnectorContext.java
core/src/main/java/io/camunda/connector/test/inbound/InboundConnectorContextBuilder.java
core/src/main/java/io/camunda/connector/test/outbound/OutboundConnectorContextBuilder.java
inbound/src/main/java/io/camunda/connector/inbound/configs/LocalContextBeanConfiguration.java
inbound/src/main/java/io/camunda/connector/inbound/webhook/InboundWebhookRestController.java
inbound/src/main/java/io/camunda/connector/inbound/webhook/WebhookConnectorProperties.java
inbound/src/test/java/io/camunda/connector/inbound/WebhookControllerPlainJavaTests.java
inbound/src/test/java/io/camunda/connector/inbound/webhook/InboundWebhookRestControllerTest.java
runtime-util/pom.xml
runtime-util/src/main/java/io/camunda/connector/runtime/util/inbound/InboundJobHandlerContext.java
runtime-util/src/test/java/io/camunda/connector/runtime/util/inbound/InboundJobHandlerContextTest.java
runtime/pom.xml

Add secret handling for inbound connectors.
- Run the latest https://github.com/camunda/camunda-platform: `docker-compose -f docker-compose-core.yaml up`
- Disable running connector bundle (via Docker Desktop)
- Build the latest SDK `mvn clean package install`
- Build the latest connector with SDK (e.g., SQS)
- Put both jars with dependencies into same directory
- Export secret as environment variable, e.g. `export HMAC_SECRET='mySecretKey'`
- Run:
```
java -cp 'runtime.jar:sqs.jar' \ 
-Dserver.port=9898 \
-Dzeebe.client.broker.gateway-address=127.0.0.1:26500 \
-Dzeebe.client.security.plaintext=true \
-Dcamunda.connector.polling.enabled=true \
-Dcamunda.connector.webhook.enabled=true \
-Dcamunda.operate.client.url=http://localhost:8081 \
-Dcamunda.operate.client.username=demo \ …
```

Add secret handling for inbound connectors

---

parent/pom.xml
validation/README.md
validation/src/main/java/io/camunda/connector/validation/impl/DefaultValidationProvider.java
validation/src/test/java/io/camunda/connector/validation/User.java
validation/src/test/java/io/camunda/connector/validation/ValidationProviderTest.java

Moves from Bean Validation 3.0 to version 2.0 for better compatibility with current Java ecosystem, e.g. Spring 5 and Spring Boot 2.
BREAKING CHANGE: All validation annotations have to be renamed from `jakarta.validation.*` to `javax.validation.*`. This applies to all Connectors.
closes https://github.com/camunda-community-hub/spring-zeebe/issues/256

feat!: move to Jakarta Bean Validaton 2.0

---

parent/pom.xml

ASL 2.0 alias was missing for Apache 2.0 license
https://github.com/camunda/connectors-bundle/pull/94#
closes #

docs: add alias for Apache 2.0 license (#94)

---

parent/pom.xml

* Removes Spring Zeebe dependency management (handled in Connectors Bundle if needed).
* Manages the GCP Secret Provider module version (used in downstream projects like Connectors Bundle).
related to https://github.com/camunda/connectors-bundle/pull/100

chore(parent): manage secret provider module & remove Spring Zeebe

---

.github/workflows/CI.yml
.github/workflows/DEPLOY.yml
.github/workflows/RELEASE.yml
.github/workflows/THIRD_PARTY_NOTICE.yml

chore(GHA): use CI Nexus as co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml
https://github.com/camunda/team-infrastructure/issues/309

chore(GHA): use CI Nexus as co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml

---

.github/workflows/CI.yml
.github/workflows/DEPLOY.yml
.github/workflows/RELEASE.yml
.github/workflows/THIRD_PARTY_NOTICE.yml

Not use the Nexus cache for maven central or non camunda artifacts
Not use the Nexus cache for maven central or non camunda artifacts
Related to https://github.com/camunda/team-infrastructure/issues/309

chore(GHA): Use Nexus CI as a cache for only Artifactory
